### ISSUE TITLE
Re-design Team page

### ISSUE THREAD

**Issue by SiddheshKukade** [SiddheshKukade/acmpvgcoet#4]
https://github.com/SiddheshKukade/acmpvgcoet
<img width="1440" alt="Screenshot 2023-10-18 at 11 32 13 AM" src="https://github.com/SiddheshKukade/acmpvgcoet/assets/65951872/e3c33504-e81f-413b-b248-a939b5d93442">

**Comment by AnnaProDev** [comment]
Hi @SiddheshKukade ! I can try to do it. Could you assign this to me, please?

**Comment by SiddheshKukade** [comment]
@AnnaKondrDeveloper Sure, please go ahead.
